### ISSUE TITLE
I wrote my own shader in babylon.js, can I use it directly in babylonNative

### ISSUE THREAD

**Issue by WdsPjm** [BabylonJS/BabylonNativeExamples#6]
I wrote my own shader in babylon.js, can I use it directly in babylonNative

**Comment by bghgary** [comment]
Sorry, didn't notice this issue. Please ask questions on [our forum](https://forum.babylonjs.com/) next time.

> I wrote my own shader in babylon.js, can I use it directly in babylonNative

It should work if the shader compiles in native. If it doesn't work, please let us know what your shader looks like.
